ALTER TABLE shipments
ADD COLUMN IF NOT EXISTS origin VARCHAR(150);

ALTER TABLE shipments
ADD COLUMN IF NOT EXISTS destination VARCHAR(150);

ALTER TABLE shipments
ADD COLUMN IF NOT EXISTS eta VARCHAR(50);

ALTER TABLE shipments
ADD COLUMN IF NOT EXISTS risk_score FLOAT DEFAULT 0.0;
